/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.scheduler.jsonc --env-file=.env.example --include-runtime=false --env-interface=SchedulerEnv scheduler-env.d.ts` (hash: 417e085dcf51fc38274d59fee87d4d8d)
interface __BaseEnv_SchedulerEnv {
	CRON_SECRET: string;
	STRESSSIGNAL: Fetcher /* stresssignal */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/scheduler");
	}
	interface Env extends __BaseEnv_SchedulerEnv {}
}
interface SchedulerEnv extends __BaseEnv_SchedulerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CRON_SECRET">> {}
}
