import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const sourceDirectory = path.join(root, "content", "articles");
const outputPath = path.join(
  root,
  "lib",
  "content",
  "article-sources.generated.ts",
);
const slugPattern = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;

const parseScalar = (value: string): string => {
  const normalized = value.trim();
  if (normalized.startsWith('"') && normalized.endsWith('"')) {
    return JSON.parse(normalized) as string;
  }
  if (normalized.startsWith("'") && normalized.endsWith("'")) {
    return normalized.slice(1, -1).replaceAll("''", "'");
  }
  return normalized;
};

const parseDocument = (source: string) => {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) {
    throw new Error("Article must start with a YAML frontmatter block.");
  }

  const frontmatter: Record<string, string | string[]> = {};
  let listKey: string | null = null;

  for (const line of match[1].split(/\r?\n/)) {
    const listItem = line.match(/^\s+-\s+(.+)$/);
    if (listItem && listKey) {
      const current = frontmatter[listKey];
      if (!Array.isArray(current)) {
        throw new Error(`Invalid frontmatter list for ${listKey}.`);
      }
      current.push(parseScalar(listItem[1]));
      continue;
    }

    const field = line.match(/^([A-Za-z][A-Za-z0-9]*):\s*(.*)$/);
    if (!field) {
      if (line.trim().length > 0) {
        throw new Error(`Unsupported frontmatter line: ${line}`);
      }
      continue;
    }

    const [, key, rawValue] = field;
    if (rawValue.length === 0) {
      frontmatter[key] = [];
      listKey = key;
    } else {
      frontmatter[key] = parseScalar(rawValue);
      listKey = null;
    }
  }

  return { frontmatter, body: match[2].trim() };
};

const documents = Object.fromEntries(
  fs
    .readdirSync(sourceDirectory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".mdx"))
    .map((entry) => entry.name.slice(0, -".mdx".length))
    .filter((slug) => slugPattern.test(slug))
    .sort()
    .map((slug) => {
      const source = fs.readFileSync(
        path.join(sourceDirectory, `${slug}.mdx`),
        "utf8",
      );
      return [slug, parseDocument(source)];
    }),
);

const generated = `// This file is generated by scripts/generate-article-sources.ts.\n// Edit content/articles/*.mdx, then run pnpm content:generate.\n\nexport const ARTICLE_DOCUMENTS = ${JSON.stringify(documents, null, 2)} as const;\n`;
const checkOnly = process.argv.includes("--check");

if (checkOnly) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";
  if (current !== generated) {
    throw new Error(
      "Article source manifest is stale. Run `pnpm content:generate`.",
    );
  }
} else {
  fs.writeFileSync(outputPath, generated, "utf8");
}
